version: '3'

vars:
  registry: "docker.io"
  userspace: "sebt3"
  image_name: 'code-server'
  #image_name:
  #  sh: 'basename $(pwd)'
  #plateforms: linux/arm64/v8,linux/amd64
  plateforms: linux/amd64
  version:
    sh: sed 's/,.*//' < .tags
  command: '{{ eq .buildkit_bin "" | ternary .docker_cmd .kubectl_bin }}'

tasks:
  default:
    deps: [build]
  build:
    cmds:
      - 'kubectl build --platform "{{ .plateforms }}" -t "{{ .registry }}/{{ .userspace }}/{{ .image_name }}:{{ .version }}" . --registry-secret docker-io --push'
  kaniko:
    cmds:
      - 'kubectl kaniko -d "{{ .registry }}/{{ .userspace }}/{{ .image_name }}:{{ .version }}" -c . --registry-secret docker-io'
